name: Publish and Deploy to Github Pages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Deve publicar em debug pq classes sao deletadas no trimming
      - name: Publish app
        run: dotnet publish -c Debug 
      - name: Rewrite base href
        uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
        with:
          html_path: ${{ env.PUBLISH_DIR }}/index.html
          base_href: /src/VisualizadorDeSinais.Browser/bin/net7.0/Debug/AppBundle/

      - name: GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v1.5.1
        with:
          target_branch: gh-pages
          build_dir: ${{ env.PUBLISH_DIR }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
